#!/usr/bin/env bash
# Link the tracked agent configuration into ~/.claude and ~/.codex.
#
# Safe to re-run. Resolves its own location, so moving this repository and
# running it again repoints every link. Existing real files are backed up with a
# timestamp, never overwritten in place.
#
# Usage: agent-setup/install.sh [--dry-run]

set -euo pipefail

SETUP_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
STAMP=$(date +%Y%m%d-%H%M%S)
DRY_RUN=0

if [[ ${1:-} == --dry-run ]]; then
  DRY_RUN=1
fi

run() {
  if [[ $DRY_RUN == 1 ]]; then
    printf '  would run: %s\n' "$*"
    return 0
  fi

  "$@"
}

# Point linkname at target, preserving anything real that is already there.
link() {
  local target=$1 linkname=$2

  if [[ ! -e $target ]]; then
    printf 'MISSING  %s\n         target does not exist: %s\n' "$linkname" "$target"
    return 1
  fi

  if [[ -L $linkname ]]; then
    local current
    current=$(readlink "$linkname")

    if [[ $current == "$target" ]]; then
      printf 'ok       %s\n' "$linkname"
      return 0
    fi

    run rm "$linkname"
    printf 'RELINKED %s\n         was: %s\n' "$linkname" "$current"
  elif [[ -e $linkname ]]; then
    run mv "$linkname" "$linkname.backup-$STAMP"
    printf 'BACKED   %s -> %s\n' "$linkname" "$(basename "$linkname").backup-$STAMP"
  else
    printf 'LINKED   %s\n' "$linkname"
  fi

  run mkdir -p "$(dirname "$linkname")"
  run ln -sfn "$target" "$linkname"
}

printf 'Installing from %s\n\n' "$SETUP_DIR"

run mkdir -p "$HOME/.claude" "$HOME/.codex"

printf 'Claude Code\n'
link "$SETUP_DIR/claude/settings.json" "$HOME/.claude/settings.json"
link "$SETUP_DIR/claude/hooks" "$HOME/.claude/hooks"
link "$SETUP_DIR/claude/agents" "$HOME/.claude/agents"
link "$SETUP_DIR/claude/commands" "$HOME/.claude/commands"

# Claude resolves a relative @import against the file holding it, which is
# ambiguous through a symlink. Generating absolute imports sidesteps that and is
# what lets a moved repository be fixed by re-running this script.
CLAUDE_MD="$HOME/.claude/CLAUDE.md"

if [[ -e $CLAUDE_MD && ! -L $CLAUDE_MD ]] && ! grep -q 'Generated by agent-setup/install.sh' "$CLAUDE_MD" 2>/dev/null; then
  run mv "$CLAUDE_MD" "$CLAUDE_MD.backup-$STAMP"
  printf 'BACKED   %s -> CLAUDE.md.backup-%s\n' "$CLAUDE_MD" "$STAMP"
fi

if [[ -L $CLAUDE_MD ]]; then
  run rm "$CLAUDE_MD"
fi

if [[ $DRY_RUN == 1 ]]; then
  printf '  would write: %s\n' "$CLAUDE_MD"
else
  cat >"$CLAUDE_MD" <<EOF
<!-- Generated by agent-setup/install.sh. Edit the imported files instead. -->

@$SETUP_DIR/AGENTS.md

@$SETUP_DIR/claude/CLAUDE.md
EOF
fi

printf 'WROTE    %s\n' "$CLAUDE_MD"

printf '\nCodex\n'
link "$SETUP_DIR/AGENTS.md" "$HOME/.codex/AGENTS.md"
link "$SETUP_DIR/codex/hooks.json" "$HOME/.codex/hooks.json"
link "$SETUP_DIR/codex/hooks" "$HOME/.codex/hooks"

printf '\nDone. Verify with: %s/verify.sh\n' "$SETUP_DIR"
printf 'Restart Claude Code, then run /context to confirm the memory files loaded.\n'
